// console.log(working);


// Asynchronous

// let start = "start of script";
// let end = "End of script";
// console.log(start);
// console.log(end);

// setTimeout(function(){
//     console.log("first timeout completed 1");
// },1000);
// setTimeout(function(){
//     console.log("first timeout completed 5");
// },5000);
// setTimeout(function(){
//     console.log("first timeout completed 2");
// },2000);
// setTimeout(function(){
//     console.log("first timeout completed 3");
// },3000);
// setTimeout(function(){
//     console.log("first timeout completed 4");
// },4000);
// Syntax
// setTimeout((){

// },Time)


// setTimeout(() => {
//     console.log("fist");
// },6000)


// const myInterval = setInterval(() =>{
//     console.log("Time Out");
// },1000)
// console.log(myInterval);



// function mainfunction(callback){
//     console.log("performing a some operstion");

//     setTimeout(() =>{
//         console.log("operstion completed");
//     },1000)
// }

// function callbackFunction(result){
//     console.log("result:", result);
// }

// mainfunction(callbackFunction);

    





